### ISSUE TITLE
Links to comprehensive area projects defined by geographic polygons

### ISSUE THREAD

**Issue by goatchurchprime** [GrottoCenter/grottocenter-front#828]
This database misses the fact that almost all cave data is collected and maintained by geographical area projects rather than by individual cave entrance.  For example [all the caves in Virginia, USA](https://virginiacaves.org/project-areas), all the caves in the [Matienzo Area, Spain](http://matienzocaves.org.uk/page1.php), the [welsh cave registry](http://www.cambriancavingcouncil.org.uk/registry/ccr_registry_view.php?ID=2014-2) or the very formal [kataster system in Austria](https://hoehle.org/downloads/Gebirgsgruppen.pdf).

Where such a project exists, it should be possible to draw a geographical polygon around its area of interest so that the cave records here can be index linked through to the corresponding cave pages in those working databases, because it can't be reasonable to copy the information from those database to here one cave at a time.

**Comment by urien** [comment]
Hi @goatchurchprime ,

Currently two students (@MargotGeorget and @Ophelux) are working so that the page of a country and on the page of a massif we see statistics as well as all the caves and indications on the quality of the existing data.
An example of a current page, their work will be available before the end of January)

https://grottocenter.org/ui/countries/GB
https://grottocenter.org/ui/massifs/1

The Matienzo massif already exists but you have to draw the polygon to see the caves that are in this massif.
You can also create the Massifs you need.

There are no tools yet to view state or county caves, but this is something we want to work on.

We have a tool that allows us to import data from other databases.
We have already used it for thousands of caves and for tens of thousands of documents. It works very well.

To be able to import the data it's necessary that the data is accessible and that it is placed under a free license.
This is the case with many databases. Sometimes they concern a very limited sector, sometimes they concern a continent. Sometimes there is a website where we can consult them, sometimes it's just a file that we are given.

We have a tool that allows you to re-import data to update them on Grottocenter, it will probably have to be improved, but it works.
We don't have tools to detect duplicates and to merge them. We started working on this feature to be able to do it by hand.

Grottocenter is a project of the Wikicaves association which aims to promote the sharing of data on the underground environment.
Shared data is data that other sites can download and reuse. This is the case of Grottocenter data which is used by using APIs.
When importing data from another site into Grottocenter we should be able to indicate this more clearly on the cave page. For the moment it is done as on this page
https://grottocenter.org/ui/entrances/75641

Do you participate in the projects you have indicated? Do you think it would be possible to work together to organize data sharing?

**Comment by urien** [comment]
To do what you propose it's possible on the page of a massif to indicate the site where it's possible to consult data. For the moment it is not possible to add text on the page of a country. If it seems useful to you, it's not very difficult to do.

**Comment by urien** [comment]
The Virginia site provides links to the Colorado or Georgia records.
These pages no longer exist.
http://www.coloradocaves.org/
http://www.caves.org/survey/gss/
Maybe the register is at another address? Maybe it's no longer available?

This is a common problem: we have exchanges with many groups, national federations, which have data but which no longer have the human resources to deal with it.
We think it is useful for the data to be shared on Grottocenter so that it is kept over time, reused by those who need it and prevents it from disappearing.

**Comment by urien** [comment]
@goatchurchprime It is already possible to create a massif and put a text and a link to an existing DB. If this corresponds to your request, I suggest that you close this ticket.

**Comment by goatchurchprime** [comment]
If you have fixed this ticket then close it yourself and take the credit. You shouldn't want me to close it since I didn't do any of the work.

To summarise: the massif data structure can be used to link to cave databases that have been made for particular terrorities. (The database doesn't care that these are not always the same as a massif.)

**Comment by urien** [comment]
ok
