### ISSUE TITLE
[Entry show] Pas d'affichage du nom de l'entrée

### ISSUE THREAD

**Issue by urien** [GrottoCenter/grottocenter-front#933]
**Describe the bug**
Pour les entrées
https://grottocenter.org/ui/entrances/89227
https://grottocenter.org/ui/entrances/88584

Le nom et la langue ne s'affichent pas.
Lorsqu'on édite l'entrée le nom s'affiche bien mais la langue du nom de l'entrée n'est pas renseigné et cette information n'est pas conservée lorsqu'on l'enregistre.
Si on modifie le nom de l'entrée celui-ci ne s'affiche pas mais il est bien enregistré et visible lorsqu'on édite l'entrée

**To Reproduce**
Aller sur https://grottocenter.org/ui/entrances/89227 visualiser l'entrée et l'éditer

**Comment by vmarseguerra** [comment]
Le problème venait du fait que l'entrance n'avait pas d'entité name associée.
En cherchant dans la base de données il y avait 6 autres entrances avec le même problème (88520, 88539, 88584, 88638, 88966, 89227).

C'est corrigé.

**Comment by BTHOM** [comment]
Merci Vincent,As tu idée de la raison de ces anomalies, sachant que, si j'ai bien compris, l'enregistrement associé "cavité" ("cave") est créé automatiquement par défaut lorsqu'on crée une "entrée" ("entrance") ?Frédéric, Ces enregistrements semblent faire partie d'une série de données, issues de la base IKARE, que tu as importées. As tu remarqué une situation ou un fonctionnement anormal lors de la saisie de ces enregistrements ? Si c'est le cas, un paragraphe pourrait mettre en garde les contributeurs dans le manuel d'utilisation.Bonne fin de dimanche à tous.BTHenvoyé : 17 septembre 2023 à 15:35de : Vincent Marseguerra ***@***.***>à : GrottoCenter/grottocenter-front ***@***.***>cc : Subscribed ***@***.***>objet : Re: [GrottoCenter/grottocenter-front] [Entry show] Pas d'affichage du nom de l'entrée (Issue #933) Le problème venait du fait que l'entrance n'avait pas d'entité name associée. En cherchant dans la base de données il y avait 6 autres entrances avec le même problème (88520, 88539, 88584, 88638, 88966, 89227).C'est corrigé.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by vmarseguerra** [comment]
Hello,

En effet lors de la création d'une cavité plusieurs entités sont créées dans la base et notamment une "cave" et une "entrance" mais ce n'était pas le problème ici:
L'architecture la base de donné prévoit que les entrances (tout comme les caves, organisations et massifs) peuvent avoir plusieurs noms (relation 1:n), les noms sont donc stockés dans une table séparée. Le problème était que l'entrance avait bien été crée mais aucun nom n'y était associé dans l'autre table, d'où le fait qu'il apparaissait vide.

Il est difficile de connaitre la raison exacte du problème sans les logs du serveur, peut-être un problème sur le format du nom, ou une exception non gérée...
Au final ça reste un problème très marginal puisqu'il ne concernait que 6 entrances sur près de 70000

**Comment by BTHOM** [comment]
Bonjour Vincent,Merci pour ton explication claire et pour l'entretien de la base de données.Pour revenir sur un autre sujet, à savoir celui du moteur de recherche, j'ai bien noté que le nombre de réponses avait été limité à 10 000 pour ne pas surcharger le serveur. Sans abandonner ce principe ni cet ordre de grandeur, serait il possible de rehausser légèrement ce plafond (disons à 12 000 environ) de façon à ce qu'on puisse vérifier le nombre d'entrées dans chaque division administrative (et notamment dans chaque région française) ? En effet, en Occitanie, nous avons aujourd'hui 10 688 entrées, si on en croit la somme des entrées par département (cf. tableau de statistiques et de contrôles de cohérence : https://wiki.grottocenter.org/wiki/GrottoCenter:Fr/Statistiques-FR#R%C3%A9gion_Occitanie_(OCC) )Encore merci et bonne journée à tous.BTHenvoyé : 18 septembre 2023 à 23:10de : Vincent Marseguerra ***@***.***>à : GrottoCenter/grottocenter-front ***@***.***>cc : BTHOM ***@***.***>, Comment ***@***.***>objet : Re: [GrottoCenter/grottocenter-front] [Entry show] Pas d'affichage du nom de l'entrée (Issue #933) Hello,En effet lors de la création d'une cavité plusieurs entités sont créées dans la base et notamment une "cave" et une "entrance" mais ce n'était pas le problème ici: L'architecture la base de donné prévoit que les entrances (tout comme les caves, organisations et massifs) peuvent avoir plusieurs noms (relation 1:n), les noms sont donc stockés dans une table séparée. Le problème était que l'entrance avait bien été crée mais aucun nom n'y était associé dans l'autre table, d'où le fait qu'il apparaissait vide.Il est difficile de connaitre la raison exacte du problème sans les logs du serveur, peut-être un problème sur le format du nom, ou une exception non gérée... Au final ça reste un problème très marginal puisqu'il ne concernait que 6 entrances sur près de 70000—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
